name: Java compile with Maven

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build-cardgame-webserver:

    name: 'Build cardgame webserver'

    uses: sebastien-perpignane/my-workflows/.github/workflows/mvn-java-workflow.yml@main
    with:
      java-version: '17'
      distribution: 'temurin'
